name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 1. Metrics (Left) - Habits & Activity
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.left.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories
          config_timezone: America/Sao_Paulo
          config_order: base.header, base.activity+community, base.repositories, habits
          
          # Coding Habits
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
          # Lines of code changed
          plugin_lines: yes

      - name: 2. Metrics (Right) - Languages & Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.right.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          config_timezone: America/Sao_Paulo
          
          # Languages
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          
          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
